name: Run Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: echo "JWT_SECRET=supersecret" >> $GITHUB_ENV
        run: echo "JWT_REFRESH_SECRET=refreshsupersecret" >> $GITHUB_ENV

      - name: Run tests with Vitest
        run: npm run test -- --run
